/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.thesimpleteam.simplebotplugin.app;

import net.thesimpleteam.simplebotplugin.BasePlugin;
import net.thesimpleteam.simplebotplugin.app.clicommands.HelloWorldCLICommand;
import net.thesimpleteam.simplebotplugin.app.commands.PingCommand;
import net.thesimpleteam.simplebotplugin.app.listener.ExampleListener;

public class App extends BasePlugin {

    @Override
    public String getName() {
        return "simpleplugin";
    }

    @Override
    public String getAuthor() {
        return "minemobs";
    }

    @Override
    public void onEnable() {
        System.out.println("Hello World from " + this.getName());
        System.out.println("This plugin is made by " + this.getAuthor());
        getLoader().addListener(this, new ExampleListener());
        getLoader().addCLICommand(new HelloWorldCLICommand());
        getLoader().addCommands(this, new PingCommand());
    }

    @Override
    public void onDisable() {
        System.out.println("Goodbye World from " + this.getName());
    }
}
